### ISSUE TITLE
Hamburger menu drawer items should drop from right side 

### ISSUE THREAD

**Issue by Mario-paul** [Mario-paul/code-week-portfolio-project#18]
Items should drop on the right instead of left (beneath hamburger button).

**Comment by Kdiaz778** [comment]
#header li a {
  display: block;
  padding: 20px 20px;
  border-right: 1px solid #f4f4f400;
  text-decoration: none;

}
add+
#header li a {
  display: block;
  padding: 20px 20px;
  border-right: 1px solid #f4f4f400;
  text-decoration: none;
  **display: flex;
justify-content: flex-end;**

}
